apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lja9k92jb-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-23fbe3dde9.6hvu.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:331c2fd37b07cd59c52f482917816911478679ed@sha256:5c5b63faac356159047e9e58c287a1332a364f1a1d69897e75514b0351994ddd
          name: container-image
